application: 140box
version: 1
runtime: python
api_version: 1

handlers:
- url: /javascripts
  static_dir: javascripts
- url: /css
  static_dir: css

- url: /
  static_files: index.html
  upload: index.html